# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=0.1
group=com.simomett
java_version=22
# Common
minecraft_version=1.21.11
mod_name=Mycology
mod_author=SimoMett
mod_id=mycologymod
license=All-Rights-Reserved
credits=
description=
minecraft_version_range=[1.21.11, 1.22)
neo_form_version=1.21.11-20251209.172050
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.11
parchment_version=2025.12.20
# Fabric
fabric_version=0.141.4+1.21.11
fabric_loader_version=0.19.3
# NeoForge
neoforge_version=21.11.42
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
